plugins:
  #https://github.com/import-js/eslint-plugin-import
  - import
env:
  node: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules: {
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
}
"overrides": [
    {
      "files": ["*.js"],
      "rules": {
        "no-console": "off",
        "import/extensions": "off"
      }
    }
  ]